

timezone: Asia/Shanghai
lang: zh_CN

title: 小猫屋
alias_en: Neu
alias_cn: 小猫屋导航
description: A Navigation Website for BYR
keywords: 小猫屋导航, Neu, 小猫屋, Neuu, Neu, 猫屋
url: https://banszd.top
established_at: "2019-11-22T00:00+08:00"

author: 
author_url: http://banszd.top
organization: TEELAB
organization_url: 
contact: contact[at]irockbunny[dot]com

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
